// Ingredient inventory for the fridge + pantry.
// Each group has a default zone; individual items can override with `zone`.
// Zones: freezer | shelf-top | shelf-mid | crisper | door | pantry

export const ZONES = [
  { id: 'freezer', label: 'freezer' },
  { id: 'shelf-top', label: 'top shelf' },
  { id: 'shelf-mid', label: 'middle shelf' },
  { id: 'crisper', label: 'crisper drawer' },
  { id: 'door', label: 'door rack' },
  { id: 'pantry', label: 'pantry' },
]

export const INGREDIENT_GROUPS = [
  {
    label: '🥬 Veggies',
    zone: 'crisper',
    items: [
      { id: 'tomato', emoji: '🍅', name: 'Tomato' },
      { id: 'onion', emoji: '🧅', name: 'Onion' },
      { id: 'garlic', emoji: '🧄', name: 'Garlic' },
      { id: 'potato', emoji: '🥔', name: 'Potato' },
      { id: 'spinach', emoji: '🥬', name: 'Spinach' },
      { id: 'mushroom', emoji: '🍄', name: 'Mushroom' },
      { id: 'bellpepper', emoji: '🫑', name: 'Bell Pepper' },
      { id: 'carrot', emoji: '🥕', name: 'Carrot' },
      { id: 'broccoli', emoji: '🥦', name: 'Broccoli' },
      { id: 'lettuce', emoji: '🥗', name: 'Lettuce' },
      { id: 'avocado', emoji: '🥑', name: 'Avocado' },
      { id: 'corn', emoji: '🌽', name: 'Corn' },
      { id: 'cucumber', emoji: '🥒', name: 'Cucumber' },
      { id: 'zucchini', emoji: '🥒', name: 'Zucchini' },
      { id: 'lemon', emoji: '🍋', name: 'Lemon' },
      { id: 'celery', emoji: '🌿', name: 'Celery' },
      { id: 'ginger', emoji: '🫚', name: 'Ginger' },
      { id: 'sweetpotato', emoji: '🍠', name: 'Sweet Potato' },
      { id: 'cabbage', emoji: '🥬', name: 'Cabbage' },
      { id: 'eggplant', emoji: '🍆', name: 'Eggplant' },
      { id: 'asparagus', emoji: '🌱', name: 'Asparagus' },
      { id: 'peas', emoji: '🟢', name: 'Peas' },
      { id: 'arugula', emoji: '🌿', name: 'Arugula' },
      { id: 'yammakchye', emoji: '🥬', name: 'Yaw Mak Chye' },
      { id: 'bittergourd', emoji: '🫛', name: 'Bitter Gourd' },
    ],
  },
  {
    label: '🥩 Proteins',
    zone: 'shelf-mid',
    items: [
      { id: 'egg', emoji: '🥚', name: 'Eggs' },
      { id: 'chicken', emoji: '🍗', name: 'Chicken' },
      { id: 'beef', emoji: '🥩', name: 'Beef' },
      { id: 'bacon', emoji: '🥓', name: 'Bacon' },
      { id: 'sausage', emoji: '🌭', name: 'Sausage' },
      { id: 'shrimp', emoji: '🦐', name: 'Shrimp' },
      { id: 'salmon', emoji: '🐟', name: 'Salmon' },
      { id: 'whitefish', emoji: '🐠', name: 'White Fish' },
      { id: 'tuna', emoji: '🥫', name: 'Tuna (canned)' },
      { id: 'ham', emoji: '🍖', name: 'Ham' },
      { id: 'beans', emoji: '🫘', name: 'Beans' },
      { id: 'pork', emoji: '🐷', name: 'Pork' },
      { id: 'lamb', emoji: '🐑', name: 'Lamb' },
      { id: 'tofu', emoji: '⬜', name: 'Tofu' },
      { id: 'chickpeas', emoji: '🫘', name: 'Chickpeas' },
      { id: 'lentils', emoji: '🟤', name: 'Lentils' },
      { id: 'dumplings', emoji: '🥟', name: 'Frozen Dumplings', zone: 'freezer' },
    ],
  },
  {
    label: '🧀 Dairy & Fridge',
    zone: 'shelf-top',
    items: [
      { id: 'milk', emoji: '🥛', name: 'Milk' },
      { id: 'butter', emoji: '🧈', name: 'Butter' },
      { id: 'cheese', emoji: '🧀', name: 'Cheese' },
      { id: 'burrata', emoji: '🧀', name: 'Burrata' },
      { id: 'cream', emoji: '🍶', name: 'Heavy Cream' },
      { id: 'yogurt', emoji: '🍦', name: 'Yogurt' },
      { id: 'sourcream', emoji: '🥄', name: 'Sour Cream' },
      { id: 'coconutmilk', emoji: '🥥', name: 'Coconut Milk' },
    ],
  },
  {
    label: '🍞 Carbs & Grains',
    zone: 'pantry',
    items: [
      { id: 'bread', emoji: '🍞', name: 'Bread' },
      { id: 'pasta', emoji: '🍝', name: 'Pasta' },
      { id: 'rice', emoji: '🍚', name: 'Rice' },
      { id: 'flour', emoji: '🌾', name: 'Flour' },
      { id: 'oats', emoji: '🥣', name: 'Oats' },
      { id: 'tortilla', emoji: '🫓', name: 'Tortilla' },
      { id: 'breadcrumbs', emoji: '🍘', name: 'Breadcrumbs' },
      { id: 'noodles', emoji: '🍜', name: 'Noodles' },
      { id: 'croissant', emoji: '🥐', name: 'Croissant' },
      { id: 'quinoa', emoji: '🌾', name: 'Quinoa' },
      { id: 'couscous', emoji: '🟡', name: 'Couscous' },
    ],
  },
  {
    label: '🫒 Sauces, Oils & Pantry',
    zone: 'door',
    items: [
      { id: 'oliveoil', emoji: '🫒', name: 'Olive Oil' },
      { id: 'soysauce', emoji: '🍶', name: 'Soy Sauce' },
      { id: 'honey', emoji: '🍯', name: 'Honey' },
      { id: 'mustard', emoji: '💛', name: 'Mustard' },
      { id: 'vinegar', emoji: '🧴', name: 'Vinegar' },
      { id: 'mayo', emoji: '🥚', name: 'Mayo' },
      { id: 'ketchup', emoji: '🍅', name: 'Ketchup' },
      { id: 'hotsauce', emoji: '🌶️', name: 'Hot Sauce' },
      { id: 'peanutbutter', emoji: '🥜', name: 'Peanut Butter' },
      { id: 'jam', emoji: '🍓', name: 'Jam' },
      { id: 'cannedtomato', emoji: '🥫', name: 'Canned Tomato', zone: 'pantry' },
      { id: 'stock', emoji: '🍵', name: 'Stock/Broth', zone: 'pantry' },
      { id: 'salt', emoji: '🧂', name: 'Salt & Pepper', zone: 'pantry' },
      { id: 'sugar', emoji: '🍬', name: 'Sugar', zone: 'pantry' },
      { id: 'chocolate', emoji: '🍫', name: 'Chocolate', zone: 'pantry' },
      { id: 'walnut', emoji: '🌰', name: 'Walnuts', zone: 'pantry' },
    ],
  },
  {
    label: '🌿 Herbs & Spices',
    zone: 'door',
    items: [
      { id: 'cinnamon', emoji: '🟤', name: 'Cinnamon' },
      { id: 'basil', emoji: '🌿', name: 'Basil' },
      { id: 'rosemary', emoji: '🌱', name: 'Rosemary' },
      { id: 'turmeric', emoji: '🟡', name: 'Turmeric' },
      { id: 'sesame', emoji: '⚪', name: 'Sesame' },
      { id: 'nutmeg', emoji: '🟤', name: 'Nutmeg' },
      { id: 'chives', emoji: '🌿', name: 'Chives' },
      { id: 'whitewine', emoji: '🍷', name: 'White Wine' },
    ],
  },
  {
    label: '🍎 Fruit & Sweet',
    zone: 'crisper',
    items: [
      { id: 'banana', emoji: '🍌', name: 'Banana' },
      { id: 'apple', emoji: '🍎', name: 'Apple' },
      { id: 'strawberry', emoji: '🍓', name: 'Strawberry' },
      { id: 'blueberry', emoji: '🫐', name: 'Blueberry' },
      { id: 'orange', emoji: '🍊', name: 'Orange' },
      { id: 'watermelon', emoji: '🍉', name: 'Watermelon' },
    ],
  },
]

export const ALL_ITEMS = INGREDIENT_GROUPS.flatMap(g =>
  g.items.map(i => ({ ...i, zone: i.zone || g.zone }))
)

export const findItem = id => ALL_ITEMS.find(i => i.id === id)
